apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jahver/k3s-terraform-portfolio.git
    targetRevision: main
    path: gitops-app
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
